//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permits.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessRule()
        {
            this.PermitSubTypeBusinessRule = new HashSet<PermitSubTypeBusinessRule>();
        }
    
        public int BusinessRuleID { get; set; }
        public string Description { get; set; }
        public string BusinessFunction { get; set; }
        public Nullable<int> MaxLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermitSubTypeBusinessRule> PermitSubTypeBusinessRule { get; set; }
    }
}
