//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permits.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public System.Guid CarMakeId { get; set; }
        public string CarModelName { get; set; }
    
        public virtual CarMake CarMake { get; set; }
    }
}
