//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permits.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentProofType
    {
        public int DocumentProofTypeID { get; set; }
        public int DocumentID { get; set; }
        public int ProofTypeID { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual ProofType ProofType { get; set; }
    }
}
