//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permits.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitSubType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermitSubType()
        {
            this.PermitSubTypeBusinessRule = new HashSet<PermitSubTypeBusinessRule>();
            this.PermitSubTypeProof = new HashSet<PermitSubTypeProof>();
        }
    
        public int PermitSubTypeID { get; set; }
        public int PermitTypeID { get; set; }
        public string PermitSubTypeDescription { get; set; }
        public Nullable<int> PermitDuration { get; set; }
        public string PermitDurationUnit { get; set; }
        public Nullable<decimal> PermitPrice { get; set; }
    
        public virtual PermitType PermitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermitSubTypeBusinessRule> PermitSubTypeBusinessRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermitSubTypeProof> PermitSubTypeProof { get; set; }
    }
}
