//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permits.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PermitEntitiesDb : DbContext
    {
        public PermitEntitiesDb()
            : base("name=PermitEntitiesDb")
        {
        }

        public object GetRoles()
        {
            throw new NotImplementedException();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agency { get; set; }
        public virtual DbSet<AgencyPreferences> AgencyPreferences { get; set; }
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<BusinessRule> BusinessRule { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<CarMake> CarMake { get; set; }
        public virtual DbSet<CarModel> CarModel { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentProofType> DocumentProofType { get; set; }
        public virtual DbSet<PermitSubType> PermitSubType { get; set; }
        public virtual DbSet<PermitSubTypeBusinessRule> PermitSubTypeBusinessRule { get; set; }
        public virtual DbSet<PermitSubTypeProof> PermitSubTypeProof { get; set; }
        public virtual DbSet<PermitSubTypeZone> PermitSubTypeZone { get; set; }
        public virtual DbSet<PermitType> PermitType { get; set; }
        public virtual DbSet<ProofType> ProofType { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<States> States { get; set; }
        public virtual DbSet<Template> Template { get; set; }
        public virtual DbSet<UserProfiles> UserProfiles { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WebUser> WebUser { get; set; }
        public virtual DbSet<WebUserLogin> WebUserLogin { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
    }
}
