//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permits.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitSubTypeBusinessRule
    {
        public int PermitSubTypeBusinessRuleID { get; set; }
        public int BusinessRuleID { get; set; }
        public int PermitSubTypeID { get; set; }
    
        public virtual BusinessRule BusinessRule { get; set; }
        public virtual PermitSubType PermitSubType { get; set; }
    }
}
