//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permits.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitSubTypeZone
    {
        public int PermitSubTypeZoneID { get; set; }
        public int PermitSubTypeID { get; set; }
        public int ZoneID { get; set; }
        public Nullable<int> MaxPermitCount { get; set; }
    
        public virtual Zone Zone { get; set; }
    }
}
