//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permits.DataAccess
{
    using System;
    using System.Collections.Generic;
    using Managers;

    public partial class UserRoles
    {
        internal List<LOOKUPAvailableRole> UserRoleList;

        public int Id { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual WebUser WebUser { get; set; }
        public int? SelectedRoleID { get; internal set; }
    }
}
